server:
  port: 8082

spring:
  application:
    name: music-catalog

  data:
    mongodb:
      uri: mongodb://user:password@localhost:27017/musicdb?authSource=admin

springdoc:
  swagger-ui:
    enabled: true
    path: /docs